version: '3.7'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      - VIRTUAL_HOST=javanoong.com
      - LETSENCRYPT_HOST=javanoong.com
      - LETSENCRYPT_EMAIL=admin@javanoong.com
    volumes:                     
      - .:/etc/nginx/conf.d
networks:
  default:
    external:
      name: nginx-proxy