version: '3.7'
services:
  nginx:
    image: jwilder/nginx-proxy
    restart: always
    environment:
      - VIRTUAL_HOST=javanoong.com
      - LETSENCRYPT_HOST=javanoong.com
      - LETSENCRYPT_EMAIL=admin@javanoong.com
    volumes:                     
      - .:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    external:
      name: wdms_linux_default